language: objective-c
osx_image: xcode9

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

env:
  global:
    - PROJECT="ApiConnector.xcodeproj"
  matrix:
  - ACTION='build test'  PLATFORM=iOS     SCHEME='ApiConnector'         CACHE_NAME=IOS      DESTINATION='platform=iOS Simulator,OS=11.0,name=iPhone 8 Plus'
  - ACTION='build test'  PLATFORM=tvOS    SCHEME='ApiConnector-tvOS'    CACHE_NAME=TV_OS    DESTINATION='platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p'
  - ACTION='build test'  PLATFORM=macOS   SCHEME='ApiConnector-Mac'     CACHE_NAME=MAC      DESTINATION='platform=OS X'
  - ACTION='build' PLATFORM=watchOS SCHEME='ApiConnector-watchOS' CACHE_NAME=WATCH_OS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'

install:
  - carthage bootstrap --no-use-binaries --platform $PLATFORM --cache-builds

before_script:
  - set -o pipefail

script:
  - xcodebuild clean $ACTION -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty -c;

notifications:
  email: true
