language: objective-c
osx_image: xcode9.0

cache:
  directories:
  - Carthage

matrix:
  include:
    - before_install:
        - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
      script:
	- xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8 Plus'
      env: CACHE_NAME=IOS

    - before_install:
        - carthage bootstrap --verbose --no-use-binaries --platform tvOS --cache-builds
      script:
        - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector-tvOS -destination 'platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p'
      env: CACHE_NAME=TV_OS

    - before_install:
        - carthage bootstrap --verbose --no-use-binaries --platform Mac --cache-builds
      script:
        - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector-Mac
      env: CACHE_NAME=MAC

    - before_install:
        - carthage bootstrap --verbose --no-use-binaries --platform watchOS --cache-builds
      script:
        - xcodebuild clean build -project ApiConnector.xcodeproj -scheme ApiConnector-watchOS
      env: CACHE_NAME=WATCH_OS

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
