language: objective-c
osx_image: xcode8.3

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - open -a "simulator" --args -CurrentDeviceUDID 57E7D476-3A98-4107-A64D-98CA0EA13EC0
  - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector  -destination 'platform=iOS Simulator,OS=10.3,id=57E7D476-3A98-4107-A64D-98CA0EA13EC0'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
