language: objective-c
osx_image: xcode8.2

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - open -a "simulator" --args -CurrentDeviceUDID AD8E8C76-910E-437D-88C2-4D6F6EBE3355
  - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector  -destination 'platform=iOS Simulator,OS=10.2,id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
