language: objective-c
osx_image: xcode9

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

env:
  - DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone 8 Plus" PLATFORM="iOS"     ACTION="test"  CACHE_NAME="IOS"
  - DESTINATION="arch=x86_64"                                       PLATFORM="macOS"   ACTION="test"  CACHE_NAME="MAC"
  - DESTINATION="OS=10.2,name=Apple TV 1080p"                       PLATFORM="tvOS"    ACTION="test"  CACHE_NAME="TV_OS"
  - DESTINATION="OS=4,name=Apple Watch - 38mm"                      PLATFORM="watchOS" ACTION="build" CACHE_NAME="WATCH_OS"

install:
  - test -f Cartfile* && carthage bootstrap --verbose --no-use-binaries --platform $PLATFORM --cache-builds

script:
  - set -o pipefail && xcodebuild -project ApiConnector.xcodeproj -scheme ApiConnector -destination "$DESTINATION" $ACTION | xcpretty

after_success:
  - if [ $TEST == "test" ]; then
      - bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  email: true
